### ISSUE TITLE
pyrotorque dependency issue

### ISSUE THREAD

**Issue by TMD20** [kannibalox/pyrosimple#10]
So I was able to fix this error

  File "/root/.local/bin/pyrotorque", line 5, in <module>
    from pyrosimple.scripts.pyrotorque import run
  File "/root/.local/pipx/venvs/pyrosimple/lib/python3.10/site-packages/pyrosimple/scripts/pyrotorque.py", line 15, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ModuleNotFoundError: No module named 'apscheduler'

Issue seems to be that apscheduler is not installed as part of the default package from pypi

**Comment by kannibalox** [comment]
Try running `pip install 'pyrosimple[torque]'` to install the dependencies, I didn't make that clear enough in the documentation.
