### ISSUE TITLE
handle scgi_url name option in watcher 

### ISSUE THREAD

**Issue by TMD20** [kannibalox/pyrosimple#19]
I was getting an error on my end with the scgi_url job specific option.
I'm not sure if that is the root cause as I also have to pass the URL option for pyrotorque.
So the latter should have worked anyways.

The error happens at 
Line 116
 host, port = target.netloc.split(":")

It said that it only got one value from the command. I think it might be sending my url alias "media", and not the final url. Strangely I did not experience this when I was using the queue job yesterday. 

The only way I can get it to work is if use the url alias, to retrive the proper final url. Before sending it off to the rpc command

Something like
      self.proxy = rpc.RTorrentProxy(configuration.settings.connections.get(self.config["scgi_url"]) or self.config["scgi_url"] or configuration.settings.SCGI_URL)

**Comment by kannibalox** [comment]
I see what happened there, I've changed it to get the proxy directly from the active engine. The similar issue with `-U` should be fixed as well. Thanks!
