### ISSUE TITLE
Issue with query

### ISSUE THREAD

**Issue by TMD20** [kannibalox/pyrosimple#21]
I'm trying to get this query to work
rtcontrol -U media [ratio=-1 OR seedtime=-1 ] custom_1=TV => does not work
ultimately the goal is to get this to work 
rtcontrol -U media [ratio=+1 OR seedtime=+8d ] custom_1=TV => does not work

The first query should always return something if custom_1=TV has result

In my attempts to see what is going on I have tried
rtcontrol -U media ratio=-1 OR seedtime=-1 => does not work
strangely this does work
rtcontrol -U media ratio=-1 seedtime=-1 => works

The first query should always work if the second query works, unless the first query is a XOR

Lastly here is a query that has all three elements
rtcontrol -U media ratio=-1 seedtime=-1 custom_1=TV => works

However trying to do or between ratio and seedtime fails
rtcontrol -U media ratio=-1 OR seedtime=-1 custom_1=TV => does not work

**Comment by TMD20** [comment]
Here are some more queries
rtcontrol -U media custom_1=TV custom_1=TV=> works
rtcontrol -U media custom_1=TV OR custom_1=TV2 => does not work
rtcontrol -U media custom_1=TV OR custom_1=TV => does not work

**Comment by kannibalox** [comment]
The main issue was that keywords (e.g. `OR` would sometimes get interpreted as `name` conditions. That's been fixed and the queries here should work as expected. If you find any examples that continue to not work, posting the output of `-o custom_activations,ratio,custom_1` of a torrent and whether you expect it to match would be helpful.

There was also a small bug that would have caused any torrents with an empty `activations` custom key to have matched on all `seedtime` queries. Now they will only match on `seedtime==0`.

**Comment by TMD20** [comment]
If I find anything else I will keep that in mind
The custom activations part isn't working for me.

But It still outputs some useful information
`	0.0	TV	Kill la Kill S01 1080p Blu-ray Remux AVC FLAC 2.0-E.N.D
	0.0	TV	Parks.and.Recreation.S04.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR
	0.0	TV	Parks.and.Recreation.S05.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR
	0.0	TV	Parks.and.Recreation.S06.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR
	0.0	TV	Parks.and.Recreation.S07.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR
	0.0	TV	Rich.And.Shameless.S01.1080p.HMAX.WEB-DL.DD5.1.H.264-KHN
	0.0	TV	Stranger.Things.S02.2160p.DTS-HD.MA.5.1.DV.HEVC.HYBRID.REMUX-FraMeSToR
	0.3	TV	The Bear (2022) Season 1 S01 (1080p HULU WEB-DL x265 HEVC 10bit EAC3 5.1 Silence)
	0.0	TV	VICE.News.Tonight.2022.11.03.1080p.WEB.h264-BAE.mkv
`
-o custom_activations,ratio,custom_1,name"

**Comment by kannibalox** [comment]
Is `custom_activations` showing as empty? If so, you'll need to add this to your rtorrent.rc to make `seedtime`, `leechtime` and `stopped` work correctly: https://github.com/pyroscope/pyrocore/blob/master/src/pyrocore/data/config/rtorrent.d/timestamps.rc#L22-L26. Things would have matched by accident due to the aforementioned bug with empty `activations`.

**Comment by kannibalox** [comment]
@TMD20 if this still isn't working for you, try putting the custom_1 part first, e.g. `custom_1=TV OR [ ratio=-1 OR seedtime=-1 ]`. `custom_1=TV OR custom_1=TV2` should also work as well. It still needs work to make `[ ratio=-1 OR seedtime=-1 ] OR custom_1=TV` work like it should.

**Comment by TMD20** [comment]
Sorry I had some data lose
I've had to delay some things.
While trying to recover

**Comment by TMD20** [comment]
Hey sorry for the delay I was able to get my server back to functioning, and I tried the changes you suggested

snippet

```
	0.0	TV	The.Umbrella.Academy.S03.2160p.NF.WEBRip.HDR.DV.DDP.5.1.HEVC-N0TTZ
R1653615393P1653616807	0.0	TV	Tin.Star.S03.2160p.AMZN.WEB-DL.DDP.5.1.HEVC-MiON
	0.0	TV	Tower of God S01 1080p Dual Audio BD Remux DTS-HD MA-TTGA
	0.0	TV	VICE.News.Tonight.2022.11.09.1080p.WEB.h264-BAE.mkv
	0.0	TV	VICE.News.Tonight.2022.11.10.1080p.WEB.h264-BAE.mkv
R1668872842P1668872901	0.0	TV	VICE.News.Tonight.2022.11.16.1080p.WEB.h264-BAE.mkv
	0.0	TV	VICE.S09.1080p.WEB.h264-KOGi
R1652404874R1652623891P1652652006	0.001	TV	WandaVision.S01.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265-CRFW
R1654512897P1654516809	0.0	TV	When.They.See.Us.S01.2160p.NF.WEB-DL.DDP.5.1.Atmos.DoVi.HEVC-SiC
R1620974798P1620993604	0.547	TV	Young Sheldon S04 1080p WEB-DL DDP5.1 - Scene
R1619455698P1619460005	0.0	TV	Young.Justice.S01.1080p.WEB-DL.AAC2.0.H.264-iT00NZ
R1630221968P1630227605	0.0	TV	Young.Justice.S03.HDR.2160p.WEB.h265-NiXON
	0.0	TV	Young.Justice.S04.1080p.HMAX.WEB-DL.DD5.1.x264-NTb
R1653057714P1653058811	0.026	TV	Young.Sheldon.S05.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
R1654392812P1654398009	0.0	TV	[HorribleSubs] Steins Gate 0 (01-23) [1080p]
R1651464856P1651471205	0.182	TV	[Spoony] Demon Slayer - Kimetsu no Yaiba - Season 03 (Entertainment District) (WEB 1080p AAC) [Dual-Audio]
R1621893173P1621904405	0.006	TV	black-ish.S07.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
R1650614980P1650618012	0.0	TV	black-ish.S08.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb

```

**Comment by kannibalox** [comment]
No worries, glad to hear everything is working again.
