### ISSUE TITLE
incompatible with rtorrent 0.9.6 or 0.9.7 new

### ISSUE THREAD

**Issue by kvanbiesen** [kannibalox/pyrosimple#23]
pyrosimple.error.EngineError: While getting download items from RtorrentEngine connected to 0bf35a9044ef:29 [rTorrent 0.13.7/0.9.7, up 0s] via 'scgi+unix:///downloads/.rtorrent/socket': <Fault -506: "Method 'd.multicall.filtered' not defined">

Seems like this function in only added in rtorrent 0.9.8...

rtorrent  0..9.6
latest pryosimple 2.4.0.

**Comment by kvanbiesen** [comment]
Never Mind, with looking tru the code, i noticed the fast query parameter. Disabling made it work :)

**Comment by kannibalox** [comment]
Cool, I've added a quick check to hopefully make this easier to spot in the future.
