### ISSUE TITLE
Using rtorrent-ps with pyrosimple? 

### ISSUE THREAD

**Issue by stevezau** [kannibalox/pyrosimple#31]
Hi, 

Thanks for porting this to python3!

Reading the docs, I am lost on how to get rtorrent-ps working with pyrosimple

Pyroscope + rtorrent-ps sets up a bunch of torrent config files and imports.. Does pyrosimple do the same ?

When starting, it fails as the pyroadmin command has changed. For example, the existing rtorrent.rc has

```execute.throw = (cat,(pyro.bin_dir),pyroadmin),-q,--create-import,(cat,(cfg.basedir),"rtorrent.d/*.rc")
```

But that does not work with pyrosimple as the command has changed and --create-import no longer exists?

I then tried to follow https://kannibalox.github.io/pyrosimple/rtorrent-config/#rtorrent-installation but --create-rtorrent-rc also does not seem to exist?

Hoping you can point me in the right direction. 

Thanks!

**Comment by stevezau** [comment]
Umm. I just removed the --create-import line and re-used the existing config files from rtorrent-ps,. seems to work.

**Comment by kannibalox** [comment]
Yep, as you've found out, this is intended to be compatible with an existing rtorrent-ps configuration setup. I'll add a note to that effect in the documentation, since it seems to be a common misunderstanding.
