### ISSUE TITLE
`SCGI_URL` doesn't allow the use of `~` in local socket path

### ISSUE THREAD

**Issue by youk** [kannibalox/pyrosimple#34]
It is not possible to use `~` when configuring SCGI with local socket.
```
SCGI_URL = "~/.config/rtorrent/socket"
```
results in
```
File "/home/x1111/.local/lib/python3.7/site-packages/pyrosimple/io/scgi.py", line 137, in request sock.connect(target)
FileNotFoundError: [Errno 2] No such file or directory
```
while
```
SCGI_URL = "/home/user/.config/rtorrent/socket"
```
works fine.

I didn't do much debugging, but it seems that `~` is getting stripped somewhere along the way. It would also be a bit helpful if the above error message mentioned the path which was not found.

In other parts of configuration (e.g. `RTORRENT_RC`) `~` works as expected.

I am also wondering whether local socket should be picked up automatically from `.rtorrent.rc` when `SCGI_URL` is unset. I have
```network.scgi.open_local = ~/.config/rtorrent/socket```
in there, but it doesn't seem being recognized as I am getting _'You need to configure a RPC connection'_.

**Comment by kannibalox** [comment]
> I didn't do much debugging, but it seems that `~` is getting stripped somewhere along the way. It would also be a bit helpful if the above error message mentioned the path which was not found.
> 
> In other parts of configuration (e.g. `RTORRENT_RC`) `~` works as expected.

This should be fixed now. Trying to print the path any time there's an error is non-trivial, but I added it to the output in a couple more places

> I am also wondering whether local socket should be picked up automatically from `.rtorrent.rc` when `SCGI_URL` is unset. I have `network.scgi.open_local = ~/.config/rtorrent/socket` in there, but it doesn't seem being recognized as I am getting _'You need to configure a RPC connection'_.

Can you try the latest version? It looks like there were same cases where `rtcontrol` specifically wouldn't try to auto-detect from rtorrent.rc. It should definitely work in general, I've added some test cases for it.

**Comment by kannibalox** [comment]
It should be more clear now:
<details>

```
Traceback (most recent call last):
  File "/home/user/src/pyrosimple/src/pyrosimple/scripts/rtcontrol.py", line 661, in open
    self.engines[url] = rtorrent.RtorrentEngine(url, auto_open=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/pyrosimple/src/pyrosimple/torrent/rtorrent.py", line 641, in __init__
    self.open()
  File "/home/user/src/pyrosimple/src/pyrosimple/torrent/rtorrent.py", line 697, in open
    self.properties = self.system_multicall(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/pyrosimple/src/pyrosimple/torrent/rtorrent.py", line 677, in system_multicall
    for index, r in enumerate(self.rpc.system.multicall(call)):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/pyrosimple/src/pyrosimple/util/rpc.py", line 244, in __request
    return self.__request_switch(methodname, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/pyrosimple/src/pyrosimple/util/rpc.py", line 258, in __request_switch
    return self.__request_xml(methodname, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/pyrosimple/src/pyrosimple/util/rpc.py", line 137, in __request_xml
    response = self.__transport.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/pyrosimple/src/pyrosimple/io/scgi.py", line 136, in request
    sock.connect(target)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/src/pyrosimple/src/pyrosimple/scripts/base.py", line 177, in run
    self.mainloop()
  File "/home/user/src/pyrosimple/src/pyrosimple/scripts/rtcontrol.py", line 774, in mainloop
    self.open()
  File "/home/user/src/pyrosimple/src/pyrosimple/scripts/rtcontrol.py", line 663, in open
    raise error.EngineError(f"Could not load engine from url {url!r}: {e}") from e
pyrosimple.error.EngineError: Could not load engine from url '~/.rtorrrent/test.sock': [Errno 2] No such file or directory
```

</details>

**Comment by kannibalox** [comment]
> It's all pretty alien to me. Isn't it possible to have something like `InvalidConfigurationError: The path '~/.config/rtorrent/socket' specified in SCGI_URL is invalid`?
> 
> Maybe I don't understand something about the Python world. Nevermind.

No, it's a fair question, the crux of the matter is that the URL is perfectly valid, but the file it's pointing at can't be found. It's similar to how a HTTP URL can be valid, but that doesn't mean the server it's pointing at is up and running. On the other side of things, `xxxxxx://127.0.0.1:8877` would be an invalid URL, and it fails with `Unsupported scheme in URL 'xxxxxx://127.0.0.1:8877'`, which while admittedly also a little mysterious indicates that it couldn't be parsed in the first place. This isn't really anything python specific, it's just general good practice to be specific about which step failed. Unfortunately as you've seen it can be difficult to balance that against the need to clearly indicate the problem to users less familiar with the ins and outs of a specific project.
