### ISSUE TITLE
pyroadmin --create-rtorrent-rc doesn't create .rtorrent.rc

### ISSUE THREAD

**Issue by govardha** [kannibalox/pyrosimple#42]
Hello,

Thanks for your effort in updating the much beloved pyrocore suite.  I found a minor issue in the documentation.

https://kannibalox.github.io/pyrosimple/rtorrent-config/#timestamps

The documentation ought to read

`pyoadmin config --create-rtorrent-rc`

Thank you!

**Comment by kannibalox** [comment]
Fixed, thanks for the heads up!
