### ISSUE TITLE
Installation of pyrosimple doesn't include config.py

### ISSUE THREAD

**Issue by govardha** [kannibalox/pyrosimple#45]
Hello, 

I did a simple install of pyrosimple using pip which seems to go fine, but then when I run a debug of rtxmlrpc to see what I am doing wrong, I get the following message, where I am told the config.py is missing.  Shouldn't the install just get the config.py and install it in place?

Thank you!

foo@asdfd:~$ rtxmlrpc --debug load.start '' 'Musical.torrent' "d.directory_base.set=\"$data_dir\"" "d.priority.set=1"
DEBUG:pyrosimple.scripts.rtxmlrpc.RtorrentXmlRpc:Options: args=['', 'Musical.torrent', 'd.directory_base.set=""', 'd.priority.set=1'], as_import=False, log_level=10, method='load.start', output_format='pretty', print_completion=None, repl=False, session=False, url=None
**DEBUG:pyrosimple.config:**Configuration file '/home/foo/.config/pyrosimple/config.py' not found.****
DEBUG:pyrosimple.config:Loading rtorrent config from '/home/foo/.rtorrent.rc'
DEBUG:pyrosimple.config:rtorrent.rc: network.scgi.open_local = /var/run/foo/.rtorrent.sock
DEBUG:pyrosimple.util.rpc:method 'load.start', params ('', 'Musical.torrent', 'd.directory_base.set=""', 'd.priority.set=1')
0
DEBUG:pyrosimple.scripts.rtxmlrpc.RtorrentXmlRpc:RPC stats: 1 requests (423 bytes) in 0.0s (response 140 bytes)
INFO:pyrosimple.scripts.rtxmlrpc.RtorrentXmlRpc:Total time: 0.008 seconds.

**Comment by kannibalox** [comment]
That `config.py` is completely optional, for if you want to [add your own custom fields](https://kannibalox.github.io/pyrosimple/custom-code/#custom-fields). If there's a custom field useful and stable enough that it should be present everywhere, I just add to the core fields.
