### ISSUE TITLE
Unable to check version number

### ISSUE THREAD

**Issue by youk** [kannibalox/pyrosimple#46]
`rtcontrol --version` prints 
```
rtcontrol unknown on Python 3.7.3
```
Other tools don't output version number too.

Versions checked:
pyrosimple-2.9.1, pyrosimple-2.10.0

**Comment by kannibalox** [comment]
Looks like it's a python 3.7 specific issue. I should be able to fix it, but ultimately it's harmless. I don't have any plans to drop support for 3.7 right now, but it is end of life, so you might want to consider using a newer version if you can.
