### ISSUE TITLE
`hashcheck` is not available

### ISSUE THREAD

**Issue by youk** [kannibalox/pyrosimple#51]
I just found out that `hashcheck` from `pyrocore` is not present in `pyrosimple`. Now I am wondering whether this omission is intentional.

**Comment by kannibalox** [comment]
Yep it was intentionally removed, since `lstor --check-data <path>` now does the same thing: https://kannibalox.github.io/pyrosimple/migrate/#hashcheck

**Comment by kannibalox** [comment]
> Is it so that there is no flag to suppress output (in case only exit code is needed)?

Try this on the latest code: `lstor -o '' -q --check-data <path>`. That will disable the progress bar and output no information about the torrent.

**Comment by kannibalox** [comment]
That will surprise all non-fatal messages, so it's still possible to get output. If you really want to discard absolutely all output, shell constructs are probably the best option: `lstor <stuff> 2>&1 >/dev/null`

**Comment by kannibalox** [comment]
Hm, fair points on all accounts. Not stopping the hash check on the first failure was definitely a holdover, and most of the things you mentioned have been fixed, however `-q` will continue to suppress non-fatal error messages.

> BTW, the mention of -H on https://kannibalox.github.io/pyrosimple/usage-tor/#lstor seems invalid/obsolete:

Thanks, fixed as well, I would've liked to have used `-H`, but chtor was already using it for adding fast-resume information.
