### ISSUE TITLE
Moving completed torrents

### ISSUE THREAD

**Issue by darkalchemy** [kannibalox/pyrosimple#55]
If I run this command:
```
rtcontrol alias=TRK realpath="$HOME/torrents/rtorrent" --move-and-set "$HOME/torrents/TRK"
```
nothing gets moved and there is no output.

If I run the this one:
```
mkdir -p $HOME/torrents/TRK
rtcontrol --to-view=trk-to-move alias=TRK realpath=$HOME/torrents/rtorrent is_complete=yes
rtcontrol --from-view=trk-to-move // --yes \
  --stop \
  --spawn "mv {{item.path}} /$HOME/torrents/TRK" \
  --exec "directory.set=$HOME/torrents/TRK" \
  --flush \
  --start
rtcontrol --modify-view=trk-to-move --alter=remove realpath=$HOME/torrents/TRK
```

I get this:
```
Filtered 0 out of 10391 torrents using [ OrNode["AndNode['PatternFilter', 'PatternFilter', 'BoolFilter']"] ]
```
and nothing gets moved.

I've missed something, but I can't figured out what it is. Could you tell me what I'm missing to get the completed torrents moved.

Thanks

**Comment by kannibalox** [comment]
`alias=TRK realpath="$HOME/torrents/rtorrent"` is meant to be placeholders for your specific setup. If you leave them as-is, no torrents will match and nothing will happen, as you found out. You may want to try running the commands without the `--move-and-set "$HOME/torrents/TRK"` at first to ensure it's selecting the torrents you expect.
As an example, if you want to see what the alias and realpath are for all your torrents, you can run `rtcontrol -o alias,realpath //` to see them, and then add whatever filters you want to narrow it down to the correct subset.

**Comment by darkalchemy** [comment]
Ok, I didn't understand how the alias worked. I removed all references to the alias and it appears to be working now. At least I'm seeing the first step in progress.

Thanks

**Comment by darkalchemy** [comment]
I have it right, now. I had to wrap the item.path in quotes and add 'd.' to directory.set. So, it looks like this now:
```
mkdir -p $HOME/torrents/Ebooks
rtcontrol --to-view=trk-to-move realpath="$HOME/torrents/rtorrent/*" is_complete=yes
rtcontrol --from-view=trk-to-move // --yes \
  --stop \
  --spawn "mv \"{{item.path}}\" $HOME/torrents/Ebooks" \
  --exec "d.directory.set=$HOME/torrents/Ebooks" \
  --flush \
  --start
rtcontrol --modify-view=trk-to-move --alter=remove realpath=$HOME/torrents/Ebooks
```

This project is awesome, thought I was going to lose pyro tools when I installed fresh on deb12 and python2 just wasn't available.
