### ISSUE TITLE
"Copy Session Metafiles by Category" example

### ISSUE THREAD

**Issue by youk** [kannibalox/pyrosimple#56]
Is the below code from https://kannibalox.github.io/pyrosimple/advanced/#copy-session-metafiles-by-category supposed to work? It gives me `jinja2.exceptions.TemplateSyntaxError: unexpected char '\\' at 45`. It seems it was copied as is from `pyrocore` documentation and I don't feel like decoding this clutter of quotes and escapes.

```
target="/tmp/metafiles"
rm -rf "$target"
rtcontrol // \
    --spawn "mkdir -p \"$target/"'{{i.fetch(1) or \"_NOLABEL\"}}"' \
    --spawn 'cp {{i.sessionfile}} "'"$target"'/{{item.fetch(1) or \"_NOLABEL\"}}/{{item.name}}-{{item.hash[:7]}}.torrent"'
```

**Comment by kannibalox** [comment]
Unfortunately I didn't realize it would be so readily available, it's indeed a bit of a mess and I haven't gotten around to completely cleaning it up yet. In the meantime, this command should work at least for that section:
```bash
rtcontrol // \
  --spawn "mkdir -p \"$target/\""'{{d.label or "_NOLABEL" | shell}}' \
  --spawn 'cp {{d.sessionfile}} "'"$target"'"/{{d.label or "_NOLABEL" | shell}}/{{d.name|shell}}-{{d.hash[:7]}}.torrent'
```
