### ISSUE TITLE
`lstor` can't provide human-readable output when metafile has no announce URL

### ISSUE THREAD

**Issue by youk** [kannibalox/pyrosimple#61]
When a torrent is added via magnet link, upon metadata retrieval rtorrent creates corresponding `torrent` file. It has `info.files` section only and, naturally, no `announce` key. Making `lstor` work with a metafile like this requires `-o` and `-V` flags to work around "bad announce URL" error.

The problem with this workaround is that you can't have nice human-readable output when `-o` is used. Normally, it would print torrent files in the `FILE LISTING` section. In contrast, `-o info.files`, prints raw array literal (`[{'length': ..., 'path': ['...', '...']}]`). There seems no supported syntax to get access to array elements and their members. One would need to parse the output.

Another scenario is obtaining human-readable info about a torrent without announce URL. Not possible.

**Comment by kannibalox** [comment]
> There seems no supported syntax to get access to array elements and their members. One would need to parse the output.

This is a separate problem that really needs a proper member selection syntax (e.g. `["info"]["files"][0]`), given that bencode keys can be arbitrary strings/ints. I'd like to implement that at some point (more for `chtor` than `lstor`), but I'd highly recommend [`jq`](https://github.com/jqlang/jq) for any kind of complex JSON processing. While I do aim to keep the default output as stable as possible, the JSON output from `--raw` (which can be influenced by `-o` to limit the fields) is intended to be the machine readable version.

> Another scenario is obtaining human-readable info about a torrent without announce URL. Not possible.

I'll have to think on it for a bit, but I don't think there's any reason that specific check can't be removed.
