### ISSUE TITLE
 'pyro._activations.append' does not exist

### ISSUE THREAD

**Issue by darkalchemy** [kannibalox/pyrosimple#62]
hi kannibalox,

Thank you for your work on pyrosimple, I use it on all of my seedboxes!

When trying to stop/cull torrents exceeding x seedtime, ```rtcontrol is_complete=yes seedtime=+72h --stop --yes``` or ```rtcontrol is_complete=yes 'seedtime>72h' --stop --yes```I get this error message. ```UserWarning: Method 'pyro._activations.append' does not exist!``` I have added the relevant lines from the sample rtorrent.rc file, but the error remains.

```
# EVENTS: Activation intervals
method.insert = pyro._activations.append, simple|private,\   
    "d.custom.set=activations,\"$cat=$d.custom=activations,$argument.0=,$system.time=\" ; d.save_resume="
method.set_key = event.download.paused, !activations, "pyro._activations.append=P"
method.set_key = event.download.resumed, !activations, "pyro._activations.append=R"
```

Full error message:
```
/home/jonnyboy/.local/pipx/venvs/pyrosimple/lib/python3.11/site-packages/pyrosimple/torrent/engine.py:728: UserWarning: Method 'pyro._activations.append' does not exist! See https://github.com/kannibalox/pyrosimple/blob/main/src/pyrosimple/data/full-example.rc#L157-L161 for an example of a configuration for using activations
  warnings.warn(
```

Is there something else I need to add to the config file or am I running the command wrong?

Thanks

**Comment by kannibalox** [comment]
That might just be a mistake in the example RC, try `simple` instead of `simple|private`. The good news is that the activation code should still be taking effect in the background, and the fields should still work correctly, it'll just nag you with the warning.

**Comment by darkalchemy** [comment]
That did the trick and no error message!

Thanks a bunch.
